### ISSUE TITLE
Callback - scdl.coffee

### ISSUE THREAD

**Issue by israeltrevino** [jariz/scdl#9]
Hello, very nice work. SCDL it is great, there is nothing similar on internet.
I installed ffmpeg in Windows, and I started to download tracks, but suddenly appears this error:

scdl.coffee:196
                  return callback(_this.output_files, downloadId);
                         ^
TypeError: callback is not a function
    at Stream.<anonymous> (C:\Users\israe\AppData\Roaming\npm\node_modules\scdl\scdl.coffee:128:32)
    at Stream.emit (events.js:187:15)
    at C:\Users\israe\AppData\Roaming\npm\node_modules\scdl\node_modules\ffmetadata\index.js:106:12
    at FSReqWrap.oncomplete (fs.js:145:20)

Maybe has to do with an empty file or with incorrect name? I appreciate your help.
Thank you
Israel Trevino

**Comment by jariz** [comment]
Hi, I haven't gotten it to work on windows myself personally.
I just used https://github.com/Miserlou/SoundScrape there and that seemed to work fairly OK
